FROM php:7-apache

WORKDIR /var/www/html

RUN apt-get update
RUN apt-get install -y unzip zlib1g-dev libpng-dev

RUN a2enmod rewrite
RUN docker-php-ext-install gd pdo pdo_mysql

USER www-data

RUN curl -sSL https://microweber.com/download.php > latest.zip
RUN unzip latest.zip
RUN rm latest.zip
