FROM php:7-apache

WORKDIR /var/www/html

RUN a2enmod rewrite

RUN apt-get update
RUN apt-get install -y unzip zlib1g-dev
RUN apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd

RUN docker-php-ext-install pdo pdo_mysql

USER www-data

RUN curl -sSL https://microweber.com/download.php > latest.zip
RUN unzip latest.zip
RUN rm latest.zip
